xzversion: 0.1

phases:
  build:
    commands:
      - mkdir /home/ec2-user/build
      - echo Build completed on `date`
      - chmod +x ./gradlew
      - ./gradlew build
  post_build:
    commands:
      - echo $(basename ./build/libs/*.jar)
      - pwd

cache:
  paths:
    - '/root/.gradle/caches/**/*'
artifacts:
  files:
    - appspec.yml
    - build/libs/*.jar
    - scripts/**


