#!/bin/bash

set -e

yum -y update
yum -y install aws-cfn-bootstrap aws-cli java-1.8.0-openjdk-headless.x86_64 python-setuptools python-pip python-software-properties
yum -y remove java-1.7.0-openjdk

mkdir -p /home/ec2-user/build
